### ISSUE TITLE
Authenticate tests not working

### ISSUE THREAD

**Issue by liepumartins** [swisnl/json-api-server#11]
Tests use `WithoutMiddleware` trait
https://github.com/swisnl/json-api-server/blob/18f07380ba0e09cd60c5eeaa406ba64628009fde/sample/Tests/SampleAuthenticationTest.php#L13

This effectively cancels all middleware, including `auth:api`, thus all `*_unauthenticated()` tests fail, because no authentication is required and operations complete same way they would for authenticated user.

**Comment by liepumartins** [comment]
I see that middleware is disabled, because tests do not make requests in `application/vnd.api+json` format. This should not be so.

Nevertheless I experimented with AuthenticationTest.php:

- removing `WithoutMiddleware` - all tests fail because requests are not in application/vnd.api+json format
- removing `WithoutMiddleware` and adding 
`        $this->withoutMiddleware([
             \Swis\JsonApi\Server\Http\Middleware\InspectContentType::class,
        ]);` so `auth:api` is not disabled. Unauthenticated tests still fail, because instead of HTTP 401, they receive HTTP 302

**Comment by liepumartins** [comment]
Some of simple tests
```
$response = $this->post($this->baseUrl);`
```
can be rewritten like
```
$response = $this->withHeaders(['Content-Type'=>'application/vnd.api+json'])->post($this->baseUrl);`
```
Or maybe set the `withHeaders()` for all tests, if possible and suits all of them.


As for 401 and 302 responses, I should double check, maybe Laravel by default does not do it and I have made it do so, somewhere. :)

**Comment by liepumartins** [comment]
Answer to 302 instead of 401 response also lies with #12 
Laravel Exception handler responds with 302 by default and 401 only if `InteractsWithContentTypes::expectsJson()` is true, which is true for ajax calls or calls with header `"Accept"` which contains either `"/json"` or `"+json"`.
Never worked with `"Content-Type"`

**Comment by bbrala** [comment]
The middleware is tested, but i agree it it nicer if the headers are checked.

Interesting find on the `Accept` header there, it seems the specification doesnt really force sending the `Accept` header though...

**Comment by bbrala** [comment]
Merged the change which adds the `withHeaders` calls.

**Comment by liepumartins** [comment]
Awesome, thank You!
