### ISSUE TITLE
Inconsistent HTTP methods

### ISSUE THREAD

**Issue by liepumartins** [swisnl/json-api-server#14]
Routes define patch method
https://github.com/swisnl/json-api-server/blob/906609f48492b0dad050403c36567c078da3759b/resources/templates/route.stub#L10

Tests tries to use put method, which is not defined
https://github.com/swisnl/json-api-server/blob/906609f48492b0dad050403c36567c078da3759b/resources/templates/authentication_test.stub#L54

Which is the correct one?

**Comment by bbrala** [comment]
I've double-checked the specification, and I would prefer PATCH since that is the request the specification uses.
