### ISSUE TITLE
The model translation package is abandoned

### ISSUE THREAD

**Issue by gundamew** [swisnl/json-api-server#31]
## Detailed description

It is an enhancement suggestion.

I saw this warning message after installing something with Composer:

> Package dimsav/laravel-translatable is abandoned, you should avoid using it. Use astrotomic/laravel-translatable instead.

And similar message displayed on [Packagist](https://packagist.org/packages/dimsav/laravel-translatable) page:

> This package is **abandoned** and no longer maintained. The author suggests using the [astrotomic/laravel-translatable](https://packagist.org/packages/astrotomic/laravel-translatable) package instead.

## Possible implementation

The author of [dimsav/laravel-translatable](https://packagist.org/packages/dimsav/laravel-translatable) suggests using the [astrotomic/laravel-translatable](https://packagist.org/packages/astrotomic/laravel-translatable) package instead.

## Your environment

* Laravel JSON API Server 0.4.0
* Laravel 5.8
* Composer version 1.8.6
* PHP 7.1.23
* macOS Mojave 10.14.5

**Comment by JaZo** [comment]
Replaced in 0.5.0
