### ISSUE TITLE
Tests fail with 404

### ISSUE THREAD

**Issue by liepumartins** [swisnl/json-api-server#6]
https://github.com/swisnl/json-api-server/blob/aa2ec67c2124d6f42005b61cf15e011281d656ca/sample/Tests/SampleAuthenticationTest.php#L29

With `dd($this->baseUrl);` one can see that url is malformed `http://localhost:8000\/samples\/`

Also instead of env('APP_URL') it is better to use config('app.url')

**Comment by Arnaudvz** [comment]
Thanks!
https://github.com/swisnl/json-api-server/commit/18f07380ba0e09cd60c5eeaa406ba64628009fde
